#!/usr/bin/env python
import sys
import re
import codecs

def getArg(argDefiner):
    for index, arg in enumerate(sys.argv):
        if argDefiner == arg:
            return sys.argv[index + 1]

filePath = getArg("-p")
flagType = getArg("-f")

banner = """
███████ ██       █████   ██████   ██████ ██████   █████   ██████ ██   ██ 
██      ██      ██   ██ ██       ██      ██   ██ ██   ██ ██      ██  ██  
█████   ██      ███████ ██   ███ ██      ██████  ███████ ██      █████   
██      ██      ██   ██ ██    ██ ██      ██   ██ ██   ██ ██      ██  ██  
██      ███████ ██   ██  ██████   ██████ ██   ██ ██   ██  ██████ ██   ██ 
"""
print(banner)

def printSolve(original, decoded):
    if original:
        print("Original: " + original)
    if decoded:
        print("Decoded: " + decoded)
    print("")

def checkForFlag(line):
    try:
        if flagType in line:
            printSolve(line, line)
    except:
        pass
    try:
        if flagType in line[::-1]:
            printSolve(line, line[::-1])
    except:
        pass
    try:
        if flagType in codecs.decode(line.encode("ascii"), "base64").decode("ascii"):
            printSolve(line, codecs.decode(line.encode("ascii"), "base64").decode("ascii"))
    except:
        pass
    try:
        if flagType in codecs.decode(line[::-1].encode("ascii"), "base64").decode("ascii"):
            printSolve(line, codecs.decode(line[::-1].encode("ascii"), "base64").decode("ascii"))
    except:
        pass
    try:
        if flagType in codecs.decode(line, "rot13"):
            printSolve(line, codecs.decode(line, "rot13"))
    except:
        pass
    try:
        if flagType in codecs.decode(line[::-1], "rot13"):
            printSolve(line, codecs.decode(line[::-1], "rot13"))
    except:
        pass

if filePath or flagType:
    with open(filePath, encoding="utf8", errors='ignore') as f:
        content = f.read()
        for word in re.sub("[^0-9a-zA-Z+/=_}{@]+", " ", content).split(" "):
            checkForFlag(word)
elif "-h" in sys.argv or "--help" in sys.argv:
    print("Flagcrack is used to find flags in files")
    print("Flagcrack will check if each line includes the flag")
    print("Flagcrack tries multiple different encodings and reverse strings")
    print("")
    print("-p: path to file with the flag you want to grab")
    print("-f: the prefix of the flag you want to grab e.g. picoCTF")
    print("")
    print("Example: flagcrack -p /file.txt -f picoCTF")
else:
    print("For help type: flagcrack -h")
